var themes = [
"Today's theme is red. Red hot? Red paint? Or something else? You decide.",
"Out and about walking? You should be! Make a photo of a street or sidewalk scene.",
"Let's play around with composition. Give us your best rule of thirds shot. Make it obvious, then reply with a link!",
"Get close! Photograph an ordinary object from as close as you can manage. Fill the frame!",
"Numbers are all around you. Find your favorite number and make a killer photo.",
"Make a photo of the loose change you receive today. Or open up the piggy bank if you need to.",
"Sunday challenge time! Approach a total stranger and make a portrait of them. Be nice!",
"How do ants see the world? Change your viewpoint. Make a photograph with your camera at floor level.",
"You might not be next to an ocean, but surely you can find some water around you to take a photo of.",
"Let's play with movement today. Get a shot of something in motion. Freeze it or let it blur. It's up to you!",
"It's Thanksgiving in the US. What are you thankful for? Make a photograph and share it with the world.",
"Many signs are immediately recognizable, but if you get in close you might find something new. Try it!",
"Blue suede, hiking, sneakers, and pumps. If only shoes could talk. Tell their story in a photo, either on or off someone.",
"Sunday challenge time! Pattern is built on repetition, like a rhythm. Make a photo of a regular or irregular pattern.",
"Happy, sad, frazzled, or stuffed to the gills? Make an abstract or literal photo that expresses how you feel today.",
"Doors can have a lot of character, be it in the hinges, knob, or style. Make a photo of a door you pass through today.",
"Let's play around with contrast today, to help train the eye for it. Make a photo that has contrasting colors.",
"One of the popular sayings among photographers is get closer and fill the frame. Make a frame filling photo today.",
"Weather affects our lives in so many ways. Make a photograph that illustrates the weather where you are today.",
"Where would civilization be without the wheel? They're all around. Make a photograph of a wheel near you.",
"Sunday challenge time! Make a photo of your favorite keepsake in soft diffuse light.",
"Today's theme is blue. Blue Monday? Blue bird? Or something else blue? Your call!",
"We can all use a little boost to get started in the morning. Make a photograph of your morning beverage of choice.",
"Black and white photographs are a classic look. Make one today and go for high contrast. Dark blacks and bright whites.",
"Most of us spend lots of time in a workspace of one kind or another. Show us your workspace in a photograph.",
"How do you relax when you just need to take a break? Make a photograph that represents this to you!",
"Lots of lights are already up for the holiday season. Festive and bright! Make a photo.",
"Sunday challenge time: Break out a bigger camera if you can and use a wide aperture to work with DOF and bokeh!",
"Show us some food you eat today, using DOF, perspective, or other tricks you've learned so far to make everyone hungry!",
"Let's try another color theme, this time make it green: green sleeves, green with envy, green eggs and ham, you name it!",
"We live in a world of noise: squeaks, honks, laughter, etc. Make a photo of a noise maker you hear today.",
"Texture adds a dimensional quality to photos, and changes with scale. Make a photo that highlights an object's texture.",
"Set your weekend on fire by making a photo of a flame today: candle, match, fireplace, or your own interpretation!",
"A perfect line can draw the eye in. Make a photo of interesting vertical, horizontal, or diagonal lines.",
"Sundays are a great day for a stroll in nature.  Make a landscape photo today, remembering the rule of thirds. Enjoy!",
"It's the season of giving. Make a photo of a holiday gift you're giving to someone, either wrapped or unwrapped.",
"Hands can tell a lot about a person: smooth, rough, dirty, or wrinkled. Make a photo of hands that tell a story.",
"Photographing animals takes patience. Make a photo of an animal today: pet, domesticated, or wild.  Focus on the eyes!",
"How do you deck the halls this holiday season?  Make a photo of your holiday decorations today.",
"It's Christmas! Make a photo that represents the spirit of this day to you.",
"Share a little bit about yourself by making a photo that exemplifies your part of the country or world.",
"Sunday challenge time: Make a portrait of a close friend or family member today and share it.",
"Trees come in all shapes and sizes. This time of year they may be covered in snow.  Make a photo of an interesting tree.",
"The contrast between an object and its shadow can make for an interesting photo. Explore the dark side of shadows today.",
"Wood has a lot of character and variety. Make a photo of something wooden today.",
"Time for a change in perspective! Look up today and make a photo that favors what's going on in the sky.",
"The new year represents opportunity. Make a photo of a scene looking out a window.",
"Yellow is an attention-getting color. Make a photograph that is dominated by yellow today.",
"Sunday challenge! Pick a focal length, any focal length, and stick with it the entire day. Post your best shot.",
"The frame of a photograph is rectilinear. Fill that frame with a circular subject today and make a photograph.",
"Reflections draw the eye. Find a pool, puddle, or other body of still water and make a photo of a reflected subject today.",
"We typically use light to illuminate a subject. Turn it around today and make a photo of a light source of any kind.",
"It's winter time here in the northern hemisphere. Make a photo with snow, frost, or ice as the theme today.",
"Glasses help many folks bring the world into focus each day.  Make a photo of a pair of any kind of glasses today.",
"The printed newspaper isn't as common as it used to be. Find a newspaper today and make a photo any way you like!",
"Challenge: Silhouettes are an interesting way to abstract a subject. Make a photo featuring a silhouetted subject today.",
"What's your favorite color? Make a photo dominated by your favorite color today and share it!",
"Someone once said Music is what feelings sound like.  Make a photo of something musical to illustrate the quote today.",
"Make a photo of something you wear to keep yourself warm and/or dry: coat, gloves, scarf, hat, you name it!",
"Play with contrasting scale today: juxtapose something small with something big!",
"Converging lines direct the viewer's eye. Sometimes found in railroad tracks, highways, and buildings. Make your photo!",
"One man's trash is another's treasure.  Make a photo of something discarded or abandoned today.",
"Sunday challenge: We've photographed many things, but few people. Make a photo where the theme is a person or people.",
"Practice the art of simplicity today by making an interesting photo from a minimalist perspective.",
"Make an interesting photo of a mode of transportation today: car, plane, bicycle, subway, or whatever you like!",
"Make your camera the star of the show today. Use another camera or mirror to put your camera in a photo of its own.",
"Quirky things often catch your eye and make for interesting art. Make a photo of something that makes you go Hmmm today.",
"Let's have some fun on a Friday. Make a photo that goes with the title (or lyrics) of a song. Interpret away!",
"We're all collectors of something. Find an interesting way to display and make a photo of a collection today.",
"Sunday challenge: Experiment with shutter speed today by making a photo with a long exposure.",
"Right (90-degree) angles can help define a composition. Make a photograph involving intersecting lines.",
"Change your perspective today.  Make a photo from a bird's eye view. Get out the chairs and ladders if you need to!",
"Take something common-an object, building, or landscape-and compose an abstract composition with it.",
"The economy is in the news all the time. Make a photo that illustrates the economy or its impact on you in some way.",
"Sugar, spice, and everything nice. Make a photo of something sweet today.",
"Get up close and personal with a building today.  Make a photo of an architectural detail.",
"Sunday Challenge: Wherever there's an edge, there's energy. Make a photo where two things meet: land-water, land-sky, etc.",
"Time for another color theme: Orange! Keep your eyes peeled for anything orange today and make an interesting photo.",
"It's Groundhog Day in the U.S. Make a photo that illustrates whether it's more like winter or spring where you live.",
"Make a sharp photo today any way you interpret it, either tack-sharp focus or a subject that is sharp itself.",
"Contrasting ideas engage the mind. Make a photo today that tells a story with contrasting elements.",
"More fun on a Friday: Make a photo that goes with the title of a movie you've seen, interpreted any way you like!",
"Curves carry the eye along with them.  Make a photo that creates a sense of movement with curves today.",
"Challenge: Practice storytelling today. Look for 3 images that tell a story, and make a set of photos that go together.",
"Pet photos are such a cliche, but they're also cute.  Make an interesting photo of a pet today.",
"Franz Kafka said Anyone who keeps the ability to see beauty never grows old. Make a photo of something beautiful today.",
"We all have some sort of hobby or favorite activity. Make a photo that shows something you enjoy doing.",
"We often get stuck in a rut of always zooming to the longest focal length. Break out today by making a wide-angle photo.",
"Continuing the Friday fun theme, make a photo that goes with the title of a book you've read.",
"Odd or even: Compose an image with an odd or even number of subjects today, and make a photo.",
"Sunday (Valentine's Day) challenge: What is love? Make an interpretive photo today. Keep it clean, people. :-)",
"It's Presidents Day in the U.S today. Make a photo with a patriotic theme for the country you call home.",
"Things are always a-changin'. Make a photo that offers a snapshot of something being built, fabricated, or assembled.",
"Fragility conveys tension. Make a photo today of a person or object in a fragile state.",
"Frames outline the focus of a subject. Make a creative photo with natural framing: windows, doors, trees, borders, etc.",
"Symbols can be simple, ornate, plain, or colorful. Make a photo of a symbol that represents or stands for something else.",
"An old adage in photography says if you want to improve your photographs, move closer. Fill your frame today!",
"Backgrounds are tricky. They can make a subject stand out or distract from it. Make a photo with a good background today.",
"Squares and grids surround us in our built environment. Focus in on some squares today and make a photograph.",
"Monochrome photos don't have to be the result of processing or desaturation. Find a monochrome composition and shoot it.",
"There is often a conflict between traditional and contemporary. Make a photo that shows this tension.",
"Negative space can be just as important to a composition as your primary subject. Explore negative space in a photograph.",
"Novelty can help goose creativity. Go somewhere today you've never been, even just a different street, and make a photo.",
"The horizon can be a strong composition element. Make a photograph that emphasizes the horizon today.",
"Sunday challenge: Make a photo that invokes or communicates happiness to the viewer. Make 'em feel it, not just see it!",
"During the Olympics, we saw many images of sports. Make your own photo of a sports activity, gear, or spirit today.",
"Find out what those buttons and dials on your camera do. Play today! Try a new setting and make a photo.",
"Weathered objects have a lot of character: cracked, rusted, bleached, etc. Give us your best weathered shot today.",
"Striped patterns have a natural pattern that catches the eye.  Find some stripes today and make a photo.",
"Food engages all the senses. Make a photograph of food that causes our mouth to water or pucker. Get the viewer engaged.",
"Lists guide an eye in a linear way: menus, recipes, etc.  As you're out and about today, find a list and make a photo.",
"Sunday Challenge: Make a photo of a sunrise or sunset today.",
"Take care of the Monday blues by picking up your camera. Make a photograph dominated by the color blue.",
"Most of us enjoy some symmetry in our lives. Look around for it today and make a symmetrical photo.",
"Street scenes capture life on the go, be it a bustling city or a quaint village. Make a photo of a street scene today.",
"Rules can be stifling if taken to extremes. Break the rules today with focus, composition, etc, and see what happens.",
"Electronic gadgets pervade our world. You've probably got several. Make a photo of your favorite gadget today.",
"Curves, squiggles, and flowing lines interest the eye. Make a photograph dominated by a curvy shape of some sort today.",
"Sunday challenge: Catchlights in the eyes make a portrait sing. Make a portrait of someone with catchlights in their eyes.",
"Trees and plants are great photographic subjects. Make a photograph of a tree or plant today.",
"Today's theme is 3. Make a photograph that features the number itself or otherwise represents 3 items.",
"Grab your camera and walk 2 minutes in any direction. Stop. Find a photo worth making from where you stopped and post it.",
"Find something that's so old it's almost timeless and make a photograph of it.",
"Change your angle today. Make a photo from 1' (30 cm) off the ground and post it.",
"Liquids can be still and reflective or in motion and chaotic. Make a photograph of something liquid today.",
"Sunday challenge: It's a new season (Spring up north, Fall down south). Make a photograph that illustrates the change.",
"Set an alarm for a random time today. Any time. When it goes off, pick up your camera and find a photo near where you are.",
"Look for angles today: 90s, 45s, or any other combination of angles that make an interesting composition.",
"Imagine you've been commissioned to photograph a product for a company's marketing dept. Give us your best product shot.",
"Time to revisit a traditional photographic look. Make a black and white photo with high contrast today.",
"Think of a subject that starts with either the letter D or S.  Find it, and make a photo!",
"Sidewalks are great for people watching. Make a photograph of a sidewalk scene today.",
"Sunday Challenge: Backlighting in a scene can create drama. Make a photo with interesting placement of backlit subjects.",
"Make a photograph today of something that produces a unique sound. Try to communicate that sound to the viewer.",
"Today's theme is the color green. Make a photograph dominated by green and post it.",
"Look for the opportunity to photograph a subject or scene in natural light today.  Pay careful attention to the exposure.",
"Health care is in the news and affects all of us one way or another. Illustrate your feeling about health care in a photo.",
"Make a fashion photo today: a person modeling clothing, the clothes in your closet, an accessory that defines you, etc.",
"Paper is versatile and malleable. From napkins to origami, it's all around. Make a photo of something made of paper.",
"Sunday challenge: Create a photograph that makes you feel happy looking at it. Don't stop at good. Go for full on happy.",
"Blue is the color of sky and water. Many call it the color of hope. Make a photo with blue and what it represents to you.",
"Speed or the sense of speed can add excitement to a photo. Make a photo of something going fast or that can go fast.",
"Henri-Cartier Bresson said Photography is nothing – it's life that interests me. Make a photo that reflects this quote.",
"Put down your big, fancy camera today. Fully engage your artistic side by making a photo with minimal gear.",
"Make a photo without composing by looking through the viewfinder: over your head, from the hip, on the ground, etc.",
"Pretend words don’t exist, only images. Make a photo today that conveys a story to those who see your work.",
"Birds are beautiful and rewarding to photograph. Challenge yourself by making a photo of a bird today!",
"Look for colors that complement each other and make a photo using complementary colors to full effect today.",
"Pretend you're a stringer for your local newspaper today. Make a photo that captures something newsworthy to you.",
"Can a picture suggest smell? Make a photograph of something that we can almost sniff and smell.",
"Every town, village, or city has distinguishing icons and landmarks.  Make a photo of one wherever you are today.",
"Bright, vivid colors can draw attention and add pop to a photo. Make a photo that has vivid colors today.",
"Break a rule today! Centered composition is generally considered boring and taboo, but can be interesting. Try it!",
"Challenge yourself with night photography today: heavenly bodies, cityscapes, landscapes, or where your muse leads you!",
"It's metal Monday! Find a metallic subject today and make an interesting photo.",
"Make a photo of something that isn't there.",
"What's your favorite type of music?  Make a photo today that in some way conveys your taste in music.",
"Spring has arrived in the Northern Hemisphere.  Make any photo that shows new life!",
"Train your eye to look for repetition. Make a photo of a repeating subject while considering composition and DOF.",
"Experiment in the digital darkroom today. Make a photo and post-process it any way you like to unleash your creativity.",
"Challenge: Side lighting can emphasize texture and add depth to a photo. Make a dramatic photo with side lighting today.",
"Plastic is everywhere. Make a photograph that illustrates a use of plastic in your life today.",
"We get energy from a variety of sources. Make a photograph of the energy that's most important to you.",
"Ansel Adams said A good photograph is knowing where to stand. Use your feet today to zoom or get a unique perspective.",
"As you walk through a door today, pick one at random, take a moment see what's around you and make a photo.",
"TGIF! To celebrate the end of the week, make an artistic shot of your favorite beverage or libation today.",
"Make two photos today of the same subject: one with deep depth of field, one with shallow. Post your favorite of the two.",
"Sunday challenge: Make a photo of something you cherish today in beautiful light. Arrange and move things if you need to.",
"Make a composition of a wall and what is against it: art, shelves, etc. Consider the rule of thirds and watch your light.",
"Find a statue, sculpture, or fountain and make a photograph of it today. Consider the time of day and light.",
"Breakfast, lunch, or dinner. Make a photograph of a yummy part of one of your meals today.",
"Find a grid pattern somewhere-maybe a brick sidewalk or ceiling tiles-and make a photo of an interesting slice of it.",
"Graffiti is something you can find almost anywhere. Make an interesting photograph of some graffiti and post it.",
"Make a photograph that illustrates the last few days of weather wherever you've been.",
"Make a photo that contains today's date in it somehow. Maybe abstract representation of the numbers. Maybe literally.",
"Pay attention to your surroundings today. Make a photo of something you walk by every day without noticing.",
"What tools do you use and appreciate on a daily basis?  Make an interesting photo of one such tool today.",
"Pick an everyday subject and get as close as you can to it. Make a photograph and post it!",
"Make a photograph with motion blur of one kind or another. Use a slow shutter speed, pan, or both.",
"Find an interesting shadow-any shadow-and make a photograph of it. Consider your framing as you shoot.",
"Make a photo that you think would work well as computer wallpaper, and try it out for a week!",
"Sunday Challenge (by popular request): Make a self-portrait, with or without the camera in the frame.",
"Black can be dramatic. Go for as much black in a photo as you can with lots of oomph, character, and depth.",
"Self-assessment is vital to artistic growth. Look thru the photos you've posted so far. Remake one you'd like to improve.",
"Make a photo today that distills some simplicity from the complexity of the world.",
"Work the angles today. Make a photo that gives us a unique perspective on an otherwise ordinary scene.",
"Fire hydrants come in many colors and forms. Make a dramatic portrait of your local fire hydrant.",
"Baskets, bags, and boxes: containers often go unnoticed. Make a photo focused on the container rather than the contents.",
"Sunday challenge time: Make a landscape photo (natural or urban). Create something that you'd want to put on your wall.",
"Today's color is purple. Maybe you'll find it on a fruit. Maybe a flower. Or, maybe a sign. Make a photo and post it.",
"Focus the viewer's attention. Make a photo of a single subject with as plain a background as you can.",
"Lose the rectangle today. Make a photograph with a square (1:1) aspect ratio and post it. Crop if needed.",
"Shiny things attract attention. Make a photograph of a shiny object and post it today. Focus in on the reflections.",
"Clocks are omnipresent in modern life. Make a photo of the clock, watch, or other device that you use most to tell time.",
"Look up today and make a photograph of the sky. Cloudy, clear, or somewhere in between? Tell the story of your sky today.",
"Sunday challenge time! Find any sort of wildlife today, and make a photo. Get in close if you can and focus on the eyes.",
"It's Memorial Day in the U.S. Make a photo that symbolizes today and what it means to you.",
"How do you get around: car, train, bicycle, plane, feet? Make a photo that represents your mode of transportation today.",
"Get down and get your knees dirty today. Find some plant life, get low to its level (close and wide), and make a photo.",
"Think of a favorite childhood sport, game, or activity. Make a nostalgic photo today.",
"Make an interpretive photo of a subject or scene that sums up your mood today.",
"Using contrast in your photography can give you very artistic shots.  Make a color photo with high contrast today.",
"Lens flare is typically avoided, but can be used deliberately to good effect. Make a photo with creative lens flare.",
"Manhole covers have character and quietly tell a story. Make a photo of a manhole cover in your neighborhood today.",
"Iteration or repetition of a subject makes for good composition. Look for a repeating pattern today and make a photo.",
"Place or find a subject floating on water today-boats, leaves, ice cubes, etc.-and make a photo!",
"Contrast subjects of different size today. Be subtle or make it obvious, it's up to you!",
"Reduce, reuse, recycle. Look for an object that has been repurposed to give it new life, and make a photo.",
"Why wait for the perfect subject? Make a photo of something that is unfinished.",
"Challenge: Invent your own filter! Shoot through something translucent or transparent. Make a photo with a unique look.",
"Make a photo of a flag today: national, state, or otherwise. Try to compose it in a unique way.",
"Constraints can unleash creativity. Walk 1 minute in any direction, stop, find a subject, and make a photo.",
"Find the shape of a letter in something around you- architecture, nature, or anything not in print-and make a photo.",
"Shoot wide open today. Make a creative photo that uses a shallow depth of field to good effect.",
"Your viewer’s eye will tend to follow a line. Make a photo that uses leading lines to direct the viewer to your subject.",
"Frame within a frame. Make a photo that uses an element-window, door, mirror, trees, etc.-to frame your main subject.",
"Make a photo that creates depth. Draw the viewer in by choosing an interesting foreground, middle-ground, and background.",
"Leave something out today. Be visually brief. Shoot tight. Make a photo that's direct and to the point.",
"Look for abstract shapes and designs today. Make a photo of a subject everyone has seen that's not easily recognizable.",
"Make a photo composed of interesting shadows today. Try composing with long shadows at the beginning and end of the day.",
"Make a photo of elements that are strikingly different from one another to add tension and interest to your composition.",
"Weekend whimsy. Make a photograph of something that tickles your funny bone. Caption it accordingly.",
"Today's color is yellow. Find something that's yellow in color and make a photograph of it.",
"Sunday challenge: Make a photograph with a photograph. Find a cherished print and compose it in a larger scene.",
"Go high key today. Make a photograph that's all bright tones or dominated by white.",
"What's your favorite device to access the Internet? Make a photograph of it today.",
"Make a photograph of something circular and crop it within a square frame.",
"Construction seems to be perpetual: streets, sidewalks, buildings. Make a photo of something under construction today.",
"Refresh from the summer heat today. Make a photo of water in motion. Freeze it or let it blur!",
"Find a sign in front of a vista that tells a story. (Don't walk on the grass.) Make a photograph and post it.",
"It's Independence Day in the U.S (fireworks!). Make a photo with celebration as the theme, wherever you are.",
"Create an optical illusion using forced perspective today. Make a distant object appear closer than it actually is.",
"Today's theme is the color blue. Blue sky. Blue plate. Blue M&amp;Ms. Make a photo of something blue and post it today.",
"Look for an area with a big differential in light. Make a photo exposed for the brightest area, isolating a subject.",
"Make a photo with the number 4 in it one way or another. Maybe 4 items. Maybe a written number. Maybe more abstract.",
"Glass is a material that's used in so many different ways. Make a photograph of a glass subject today.",
"Who are you? Make a self portrait today and show the rest of us what you look like.",
"Find a scene that's dominated by one color and make a photograph of it. Use light and shadow to accentuate detail.",
"Focus on a fragment of an object today. Make a photograph that only shows part of an object, not the whole thing.",
"Corners are everywhere. Make a photo of an interesting corner today, capturing its light and angles.",
"Make a photo from a low point of view. Go for a dramatic effect by changing the appearance of the size of your subject.",
"Get creative with abstraction today. Make a photograph of patterns and/or shapes that aren't recognizable objects.",
"Everyone loves food photos! Make a close-up photograph of food you're enjoying on a Friday. Arrange for good lighting.",
"Find something that's out of context today, natural or staged, and make a photograph.",
"Sunday Challenge: Compose an image that has a soft and dreamy look today, and make a photograph.",
"Ads promote removing wrinkles, but they often add character. Make a photo of something wrinkled, crinkled, or folded.",
"Make a photograph that emphasizes a change in texture: smooth/rough, soft/hard, shiny/dull, etc.",
"It's summer in the Northern Hemisphere. Make a photo of a cool, refreshing drink. Go for something creative.",
"Rotate your camera today a bit and make a slightly off-angle photograph. Use the angle to emphasize your subject.",
"Double your art today. Make a photo of something you've created or crafted.",
"Make a photo that uses negative space to good effect. Give your subject room to breathe, and balance it within the frame.",
"Challenge: The real world is in 3D. Make a photo that uses perspective or side light to create the illusion of depth.",
"Today's theme is the color pink. Find something that's pink and make a creative photo.",
"Today's theme is the number 6. Make a photograph of the number six, six objects, or express six in an alternate way.",
"The world is always in motion. Make a photo that conveys a bit of your own motion to your viewer.",
"Turn the tables and make a photograph of a light source today. Light bulb, window, or even the sun (be careful!).",
"Pavement comes in many flavors. Asphalt. Concrete. Bricks. Stones. Make a photo of some pavement you see today.",
"Make a portrait of somebody today. It can be somebody you know or a stranger. Maybe even yourself.",
"Go anti-bokeh today. Use a large depth of field (higher aperture numbers) today to tell a story on multiple layers.",
"Beauty is all around us.  Make a photo of some naturally occurring beauty in your area today.",
"How does your garden grow? Make a photo of something growing in your or someone else's garden today.",
"Weather affects us all.  Make a photo of weather or something affected by weather today.",
"Fabric: we wear it, sleep on it, decorate with it.  Make a photo of an interesting cloth design or texture.",
"Insects are everywhere. Photograph a bug in your environment (no spiders - they're arachnids).",
"Visit a park today-national, amusement, playground-and make a photo of something that catches your eye.",
"Challenge: Sympathy can be difficult to express in words. Make an image suitable for the cover of a condolence card.",
"Triangles keep the viewer’s eyes on a photo. Follow a triangle, and you see other elements. Make a photo with triangles.",
"Today's color is green. Make a photo of a green subject today and post it.",
"Make a photograph that uses the rule of thirds composition in a very obvious way and post it.",
"Find a repeating pattern and make a photo of it today.",
"Make a photograph using wide focal length. Zoom or prime or iPhone cameras all qualify for going wide today.",
"Make a photograph with motion blur today. Use a fast moving subject or a slow shutter speed can do the trick.",
"Make a photograph using hard light today. Feature the crisp and strong shadows as a major element of your photograph.",
"Make a photograph of a plant today. It can be a small one in a pot, a big one in the park, or a tree in a forest.",
"Make a photograph that features a sign of some sort today. Maybe a stop sign. Maybe an information sign. Or an advert.",
"Go meta and make a photo of a photo today. Don't just be a copy machine, however. Get creative with composition.",
"Make a photograph of something you eat today. Breakfast, lunch, dinner, or snack. Make it look tasty.",
"Make a photograph with a shallow depth of field today. Get in close if you need to force it with the lens you have.",
"Make a photograph from a high point of view. Get on top of a building, use a ladder, or just look down at a small object.",
"Make a photograph of something made out of glass. Be sure to go for interesting reflections or highlights.",
"Today's number is 5. Make a photo that illustrates the number in some way, either literally or abstractly.",
"Make a low key photo today with lots of dark areas. You might need to use exposure compensation to make it work.",
"Make a photo of a tool today. Screwdriver. Pliers. Computer. What's the tool you find most important on a daily basis?",
"Make a photograph with soft light today. Try to almost totally eliminate shadows on your subject.",
"Make a photograph of something metallic today. Put the emphasis on texture and light.",
"Use repetition to create an interesting photograph today. Grids, patterns, or a series of lines will all do the trick.",
"Make a photograph of something cold today. Ice cubes, frosty beverages, or the freezer aisle at the grocery store.",
"Make a photograph featuring a diagonal line or series of diagonal lines. Pull our attention through the photograph.",
"Illustrate your local weather today with a photo. Rain or shine. Cloudy or clear. Communicate what it's like to the world",
"Make a monochromoe photograph today. Either use a single color subject/background or make it monochrome in post.",
"Make a beautiful photograph of something commonly thought of as ugly.",
"Make a photograph of one of the least expensive things that you cherish.",
"Water sustains life. Color enhances life. Make a photo today combining color and water.",
"A person's hands can tell a story. Take a picture of someone's hands today.",
"Welcome the new week (and holiday in the US) by making a bright cheery photo outdoors and posting it today.",
"Make a photograph with either a 9 or 6 in it represented in some way and post it today.",
"How did you get around today? Make a photograph of your transportation and post it.",
"Make a photograph of the front of a building today. Could be your house, the bank, or city hall.",
"Find a strong series of horizontal lines or elements and make a photograph of it today.",
"Plastic or glass, make a photo of a bottle or grouping of bottles today and post it.",
"Sunday challenge: Play with scale today. Make a photo of something small that looks huge.",
"Make a photograph of a path, sidewalk, trail, or road today and post it. Lead our eye through the scene.",
"Use a door or window as a framing device to contain a smaller scene today.",
"Hard shadows can emphasize texture and edges. Find a scene with lit with hard shadows today and make a photo.",
"Preparing or eating food is a rhythmic part of life. Make a photo of a meal you prepared our ate today.",
"Showcase the beauty of living foliage! Make a photo of a single leaf or an entire greenscape today.",
"Make a photo of two complementary objects arranged in a pleasing composition, one large and one small.",
"Some carry a talisman, amulet, lucky charm, or just a comforting thing in our pocket. What do you carry?",
"Make a photograph of something that is soft, or at least looks that way. Convince the viewer of the softness.",
"Use a mirror as part of a composition in a photograph today. Show yourself in the image if you'd like!",
"Communicate chaos, disorganization or messiness in a photograph. Find some beauty in it.",
"Symmetry can be calm and soothing. Make a photo today featuring symmetry, either in subject or composition.",
"Make a photo of an interesting stack of books or magazines. Consider how you handle repeating lines in your composition.",
"Make a photograph that shows an interpretation of your favorite indulgence or guilty pleasure.",
"Fences and walls can divide or demarcate. Make a creative photo of a fence or wall today.",
"Make a photograph today dominated by browns or other earthtones. Explore how the color influences your subject choice.",
"Power plugs are ubiquitous. Can you make a creative photo of such a common thing? Try it today!",
"Create a photo that illustrates the word ouch with your own personal interpretation.",
"Make a photograph of a vanishing point today made by converging lines. See http://bit.ly/cjE62b if you need a definition.",
"Simplicity is economy. Make the simplest photograph you can today. Take things out until you can't remove anything else.",
"Make a photograph that plays two complementary colors off of each other today. See http://bit.ly/9L0FAS.",
"Make a photograph that emphasizes the horizon. It's your choice whether to place it on the third lines or to center it.",
"Bathrooms are full of hard surfaces, textures, and personal implements. Fins an inspiring photograph in a bathroom today.",
"Paper can have texture, be folded, made into an airplane, or crumpled/torn. Make something with paper, then make a photo.",
"The warmth of wood takes on many shapes and forms. Make a photograph of something made of wood today.",
"Illustrate an aspect of modern culture today. Make a photo that communicates the feeling of abandoned or discarded.",
"Make a photograph today of an interesting subject with as vertical or high a point of view as you can manage.",
"Make a silhouette today by positioning a darkly lit subject in the foreground against a brightly lit background.",
"Create a photograph with a distinctly asymmetrical composition today. Pick a subject that goes with the theme.",
"Let's start out the new week by making a photo with a red point of interest. Make sure your subject really stands out.",
"Stairs and ramps lead the eye and take us places. Make a photo of a stair or ramp that you see today.",
"Think upside down &amp; really change your view point. Make a photo where you or your subject is upside down.",
"Fire is dramatic, as it its effect. Make a picture of a flame or something changed by fire or flame.",
"Illustrate the act or emotion of tension in a photograph today.",
"Make a photograph of an edge of something today. The edge of a knife, the waters edge, or some other edge.",
"Make a photograph of three items arranged in a composition that pleases you.",
"Make a photograph of a curved line or spherical surface today.",
"Make a photograph of an object or surface that has a glint or a sparkle in it today.",
"Double your art today. Make a photo of something you've created or crafted.",
"October is breast cancer awareness month. Make a photo of something pink to support the cause.",
"Illustrate the idea of time in a photograph today. Be as literal or abstract as you want to be with your interpretation.",
"Plastic is everywhere. Make a photograph that illustrates a use of plastic in your life today.",
"Communicate motion in a still photograph. Blur is one way, but maybe there are others you can find.",
"Make a high-contrast photograph today. Keep in mind that color contrast can be as effective as black and white.",
"Make a photograph today where vertical elements or lines dominate the scene.",
"Reaching up, reaching for, reaching out, or reaching in. Show the action of reaching in a photograph today.",
"Make a photograph today that has a strongly centered composition.",
"Make a photograph with compositional elements that mimic a face. No real human faces!",
"Today, let's illustrate the emotion of being happy. Make a photograph that represents happiness to you.",
"The color of the day is orange. Make a photograph that is full of orange today.",
"There word balance has many meanings, literal and abstract. Pick one and make a photograph today.",
"A fork in the road. Casting a ballot. Buying bread. Choices abound. Illustrate making a choice today with a photo today.",
"Frames outline the focus of a subject. Make a creative photo with natural framing: windows, doors, trees, borders, etc.",
"Today, make a photo that emphasizes or even exaggerates brightness in a scene.",
"Make a photo today with a subject low in color saturation. Bonus points for not using a software slider!",
"Sometimes, the best advice is to get closer. Today, get really close to your subject. Use a macro lens if you have one.",
"Sometimes what’s out of focus can make the shot. Create a photograph today where some/all of your subject isn't in focus.",
"Radiating lines pulls the viewer directly to a center of interest. Take advantage of this in a photo you create today.",
"Isolate your subject today in a photo you create today. Eliminate every distracting element possible.",
"Gauges, meters, and turn signals are all indicators. Make a photograph of an indicator that catches your attention today.",
"Facades give buildings their public face. Make a photo of a building's facade today that tells its story.",
"Create a composition that playfully incorporates text of some sort in it today. Make it meaningful to you if you can.",
"What is your favorite material? Make a creative photograph today that emphasizes its characteristics.",
"Illustrate the word free today. Go with the first thing that pops into your head and make a photograph based on that idea",
"Make a photograph with a calendar theme today.",
"Create a photo with a single element, no distractions and lots of contrast.",
"Graffiti is unwanted by many, but can be visually interesting. Find visual interest in something you don't like today.",
"Make a photograph today that visually communicates a sound. Your choice of sound, but do your best to make us hear it.",
"Low contrast in a scene can connote softness, calmness, or mellowness. Make a photo today that has low contrast.",
"Tungsten light can often create a warming effect, depending on your white balance. Use tungsten light in a photo today.",
"Find or make a reflection in a window today and shoot through it to create a layered composition.",
"Make a photograph dominated by horizontal lines or compositional elements that go all the way across the frame.",
"Go white on white today. Make a photograph of a white subject on a white background.",
"Illustrate the process or thought of traveling today, possibly by documenting your own travels.",
"Make a photograph today that documents your family or conveys how you think of your family.",
"Containers, boxes, and packages. Make a photo with one or more as a subject and illustrate what they mean to you.",
"Go for an unusual point of view and make a photograph that can only be made from that viewpoint.",
"The dictionary defines a vista as a pleasing view. Make a photo of a vista that pleases you today.",
"Illustrate what the word vision means to you. Either be literal or interpret it broadly and artistically.",
"The Golden Ratio has been used in art for millennia. Use or illustrate the Golden Ratio in a photograph today.",
"Use vignetting in a photograph today. Either add it in post (easier) or do it in camera via lens or lighting (harder).",
"Make a photo today that features a hand in a creative way.",
"Double up on your art today. Make a photograph of something else that you've created or crafted.",
"Find a composition today with a strong line or edge that cuts from one corner of the frame to the other.",
"Illustrate or show depth of one kind or another in a photograph today.",
"Make a photograph today with strong direct light that casts crisp dark shadows.",
"Illustrate the word equality today with a photograph that shows your favorite interpretation.",
"Make a photograph of a beautiful simple shape, such as an egg, today. Utilize lighting and focus to make it sing.",
"Blue jeans and denim are pervasive. Incorporate a pair of jeans or the material into a photograph today.",
"What makes you anxious? Illustrate it in a photograph today.",
"What can make a photograph feel moody to you? Illustrate your answer today.",
"Sunday challenge! Timing can make or break a photograph. Make a photograph today that has to be timed just right to work.",
"Make a photo of a pair of subjects today. People or inanimate objects are both fair game!",
"Shoot wide open today. Make a creative photo that uses a shallow depth of field to good effect.",
"Yellow is great at grabbing attention. Make a photograph today where the primary subject is yellow in color.",
"Find a repeating pattern today and make a photograph of it.",
"Squares and grids surround us in our built environment. Focus in on some squares today and make a photograph.",
"Shoot wide open today. Make a creative photo that uses a shallow depth of field to good effect.",
"Illustrate one of the meanings of the the word warmth today in a photograph.",
"Make a photo of a hallway or passage and post it today.",
"It's the solstice. Make a photo that captures the day for you wherever you are.",
"Make a photograph of a circular or round object today.",
"Make a photograph of something metal or metallic today with an emphasis on how light interacts with the surface.",
"Today's color is red. Make a photograph dominated by the color and post it today.",
"Illustrate your idea of peace and harmony-or maybe just peace and quiet-today with a photograph.",
"What fuels your creative process? Illustrate it in a photo today.",
"Make a photograph that emphasizes the horizon today and post it.",
"Illustrate coldness in a photograph today.",
"Make a photograph with as soft a light source as you can find or create.",
"The rule of thirds is a time-honored composition guideline. Put it to use today in a photo.",
"Looking back at the year, what was your favorite memory? Illustrate it with a photograph.",
"Make a photo illustrating a fresh start, a new beginning, or the first step to a goal.",
"Find an interesting texture today and make a photograph.",
"Make a photograph with a symbol or an icon in it today.",
"Make a photograph today with a diagonal line leading the viewer's eye through the composition.",
"Make an interesting photograph of something mundane and ordinary today.",
"Go high contrast today and make a photograph with tons of pop. Do as much in-camera as possible.",
"Use strong converging lines in a photograph today. It's your choice whether or not to show the vanishing point.",
"Make a photograph today to serve as a special memory of somebody or something.",
"Embrace the shadows today and make a photograph dominated by dark tones, also known as a low-key image.",
"Create a photograph today that illustrates or shows rhythm.",
"Make a photograph today that features or uses a liquid as a subject.",
"Make a photograph of something shiny or glossy, but not transparent. Emphasize the effect of the surface.",
"Illustrate one of the various meanings of the word tag today in a photograph.",
"Let's play with movement today. Get a shot of something in motion. Freeze it or let it blur. It's up to you!",
"Make a photograph of two complementary objects arranged to show their relationship to each other.",
"Today's theme is blue. Make a photograph dominated by the color or that otherwise illustrates the theme.",
"Make a photograph with a soft look today.",
"Make a photograph with a triangular composition.",
"Make a photograph featuring a path, road, or trail that leads the eye through the photograph.",
"How low can you go? Make a photograph today from a low point of view.",
"Take color out of the equation and make a monochromatic photograph today.",
"Make a photo that features stripes of some sort today.",
"Celebrate the pretty things in life. Make a photograph of the most beautiful thing you see today.",
"Use hard light that casts sharp distinct shadows in a photograph today.",
"Make a photograph today that illustrates attraction. Pick whatever definition of the word you'd like.",
"Make a photograph today with a central point of interest in it.",
"Make a photograph that features a very distinct curved line or surface today.",
"Today's theme is red. Red hot? Red paint? Or something else? You decide. Make your photo and then reply with a link!",
"Make a photograph that illustrates an aspect of communication.",
"Make a photograph using hard light today. Feature the crisp and strong shadows as a major element of your photograph.",
"Make a photograph that features repetition.",
"Fill the frame of a photograph with a single subject today.",
"Pretend you're a stringer for your local newspaper today. Make a photo that captures something newsworthy to you.",
"Look upward today. Make a photograph with a low horizon and that emphasizes the sky.",
"Create a photo today that gives a sense of depth or dimension.",
"Go abstract today and make a photograph that focuses on form and color rather than detail.",
"Power plugs are ubiquitous. Can you make a creative photo of such a common thing? Try it today!",
"Use a window or a door as a frame for your subject today in a photograph.",
"We all prepare for things every day. Illustrate preparedness in a photograph today.",
"Make a photograph that features a leading line through it today. Draw the viewers eye through the image.",
"Change your point of view. Make a photograph from an unusual point of view today.",
"Sometimes what’s out of focus can make the shot. Create a photograph today where some/all of your subject isn't in focus.",
"Tell the story of a subject today in a photograph by photographing one specific detail of it.",
"Look up today and make a photograph of the sky. Cloudy, clear, or somewhere in between? Tell the story of your sky today.",
"Make a photograph featuring strong vertical lines today.",
"Make a photograph of something old. Be sure to show us the character that age can give a subject.",
"Make a high key photograph today dominated by bright tones.",
"Happy, sad, frazzled, or joyus? Make an abstract or literal photo that expresses how you feel today.",
"Make a photograph that features the color yellow in some way or another.",
"Make a photograph of something that captures a small bit the flavor of where you live or your culture.",
"Work with scale today and make a photograph that features a subject either larger or smaller than expected.",
"Who are you? Make a self portrait today and show the rest of us what you look like.",
"Make a photograph today that illustrates of the act of waiting.",
"Beauty is all around us.  Make a photo of some naturally occurring beauty in your area today.",
"Illustrate your idea of peace and harmony-or maybe just peace and quiet-today with a photograph.",
"Make a photograph featuring strong horizontal lines today.",
"Make a photograph that illustrates the idea of connection.",
"Make a photograph of something that is glowing today. Use any meaning of the word you like.",
"Make a photograph illustrating a sound that catches your ear today.",
"Find a repeating pattern today and make a photograph of it.",
"What kind of other art do you appreciate? Make a photograph that celebrates it today.",
"Make a photograph that features a shadow as your subject today.",
"Make a photograph of something that you find amusing today.",
"Make a low contrast photo today. Concentrate on other cues—such as line and texture—to create your photograph.",
"Make a photograph of a smile today.",
"Today's theme is red. Red hot? Red paint? Or something else? You decide. Make your photo and then reply with a link!",
"Make a feeling that conveys a sense of being outdoors today.",
"Make a photograph that features water in one way or another today.",
"Make a photograph of a beautiful simple shape, such as an egg, today. Utilize lighting and focus to make it sing.",
"Make a photograph that illustrates randomness in some way today.",
"Make a photograph that illustrates a role of technology in your life.",
"Make a photo of two complementary objects arranged in a pleasing composition, one large and one small.",
"Make a photograph today that illustrates the idea of freshness to you.",
"Today's color is green. Make a photograph dominated by green today.",
"Make a photograph outdoors without an obvious horizon line.",
"Show your own hand in a photograph today doing something. Reaching, holding, touching, or making a sign.",
"Convey warmth in a photograph today.",
"Go somewhere you've not been to in a while and make a photograph of something that grabs your interest.",
"Make a photograph that incorporates a circle.",
"What reminds you of home? Make a photograph of it today.",
"Illustrate the rule of thirds in a photograph today.",
"Make a photograph today that uses layers as a compositional tool.",
"Make a photograph featuring a path, road, or trail that leads the eye through the photograph.",
"Make a photograph of something in motion. Use blur to help convey the motion you are capturing.",
"Today, let's illustrate the emotion of being happy. Make a photograph that represents happiness to you.",
"The horizon can be a strong composition element. Make a photograph that emphasizes the horizon today.",
"Make a black and white photograph and go monochrome today.",
"Make a photograph that illustrates being inside today.",
"Make a photograph that features metal or a metallic surface today.",
"Make a photograph dominated by the color orange today.",
"Illustrate attraction in a photograph today.",
"Make a photograph of a symbol today.",
"Illustrate symmetry in a photograph today.",
"Make a photograph from an unusual point of view.",
"Focus on an edge today and make a photograph.",
"Make a photograph of something shiny today.",
"Make a low contrast photograph today.",
"Make a photograph that features a grid of some sort today.",
"Illustrate time in a photograph today.",
"Make a photograph with a central point of interest today.",
"Make a photograph the features a subject made of wood today.",
"Focus in on an interesting texture and make a photograph today.",
"Make a high-contrast photograph today.",
"Make a photograph that features repeating patterns.",
"Illustrate something technological in a photograph today.",
"Make a photograph that features you in some way.",
"Make a low-key photograph today.",
"Illustrate motion in a photograph today.",
"Illustrate connection in a photograph today.",
"Make a photograph of a smile, either literal or symbolic.",
"Make a photograph that features water today.",
"Make a low contrast photograph today.",
"Make a photograph that features the horizon.",
"Make a photograph that emphasizes converging lines.",
"Make a photograph that features a circle today.",
"Illustrate the word choice in a photograph today.",
"Make a photograph with a concrete surface in it today.",
"Make a black and white photograph today.",
"Illustrate a sound in a photograph today.",
"Make a photograph dominated by the color green today.",
"Make a photograph that illustrates an aspect of local culture today.",
"Make a photograph of something old or aged today.",
"Make a photograph of two complementary objects today.",
"Make a photograph that is composed of several layers today.",
"Illustrate randomness in a photograph today.",
"Make a photo dominated by shadows today.",
"Make a photograph of the sky today.",
"Make a photograph that features vertical lines today.",
"Make a photograph with no obvious horizon.",
"Illustrate warmth in a photograph today.",
"Make a photograph using soft light today.",
"Make a photograph dominated by the color red today.",
"Frame a view using a door or a window today.",
"Make a photograph using hard light today.",
"Make a photograph with a strong line that leads the eye through the image.",
"Make a photograph that features a silhouette today.",
"Make a photograph that features radiating lines today.",
"Illustrate cold in a photograph today.",
"Make a high contrast photograph today.",
"Make a photograph featuring a fence or a wall today.",
"Make a photograph of something made of glass today.",
"Make a photograph of a tool today.",
"Make a photograph of a vista today.",
"Make a photograph dominated by the color yellow today.",
"Make a high-key photograph today.",
"Make a photograph dominated by horizontal lines.",
"Make a photograph dominated by the color blue.",
"Make a photograph today with a central point of interest in it.",
"Make a photograph that features metal or a metallic surface today.",
"llustrate attraction in a photograph today.",
"Make a photograph dominated by the color orange today.",
"Make a photograph of a symbol today.",
"Illustrate symmetry in a photograph today.",
"Focus on an edge today and make a photograph.",
"Make a low contrast photograph today",
"Make a photograph from an unusual point of view.",
"Make a photograph that features a grid of some sort today.",
"Make a photograph of something shiny today",
"Illustrate time in a photograph today.",
"Make a photograph of something smooth.",
"Parallel lines draw the eye. Make a photograph with parallel lines today.",
"Make a photograph emphasizing a square or a grid today.",
"Don’t over-think it. Make a beautiful photograph today. And tomorrow. Keep at it and discover your own view of beauty.",
"Make another beautiful shot today, but pick a subject that’s completely different than yesterday’s.",
"Make a photograph from a high point of view. Get on top of a building, use a ladder, or just look down at a small object.",
"Make a photograph today that either contains motion blur or conveys motion in some other way.",
"The color of the day is orange. Make a photograph that is full of orange today.",
"Make a photograph that features a shadow as your subject today.",
"Make a close-up photograph of something. Fill the frame with your subject if you can.",
"Lists guide an eye in a linear way: menus, recipes, etc.  As you're out and about today, find a list and make a photo.",
"Illustrate heat in one of its many forms in a photograph today.",
"Make a photograph of water in one form or another today.",
"Make a photo of a pair of subjects today. People or inanimate objects are both fair game!",
"Work the angles today. Make a photo that gives us a unique perspective on an otherwise ordinary scene.",
"Make a photograph of two complementary objects arranged to show their relationship to each other.",
"Make a photograph today that illustrates attraction. Pick whatever definition of the word you'd like.",
"Make a monochrome photograph today. Keep in mind that monochrome doesn’t have to mean black and white.",
"Make a photograph with around the number three today. Three objects. Three colors. The number three.",
"Make a photograph that features white in a dominant manner. Use a white subject. Blow out the sky. Use your imagination.",
"Illustrate choice in a photograph today. Be obvious or subtle. Your, ahem, choice.",
"What's the first thing you think about when you see the word Deadline. Make a photograph of illustrating that thought.",
"Make a photograph today that features the sky.",
"Feature a plant in a photograph today. Domestic, wild, or anything in between is fair game.",
"Play with contrasting scale today: juxtapose something small with something big!",
"Make a photo with a strong linear composition today.",
"Pattern is built on repetition, like a rhythm. Make a photo of a regular or irregular pattern.",
"Make a photograph of something very green. Don't settle for vaguely green. Go for saturation.",
"Make a photograph today dominated by dark values.",
"Make a photo of a tool today. Screwdriver. Pliers. Computer. What's the tool you find most important on a daily basis?",
"Create a photograph that makes you happy today.",
"Make a photo that features stripes of some sort today.",
"Change your angle today. Make a photo from ground level.",
"Make a photograph dominated by the color blue.",
"Pay attention to your surroundings today. Make a photo of something you walk by every day without noticing.",
"TGIF! To celebrate the end of the week, make an artistic shot of your favorite beverage or libation today.",
"Make a photo of something you cherish today in beautiful light. Arrange and move things if you need to.",
"Make a photo of something that sparkles in some way.",
"Craft a photo using strong contrast between very light and very dark areas.",
"Make a photograph today of something that you've not made a photograph of before.",
"Stairs and ramps lead the eye and take us places. Make a photo of a stair or ramp that you see today.",
"Make a photograph today that features the use of low contrast to create a mood or feeling.",
"Make a photograph featuring nature in some fashion.",
"Lose the rectangle today. Make a photograph with a square (1:1) aspect ratio and post it. Crop if needed.",
"Make a photograph of something made out of glass today.",
"Find something beautiful and make a photo. Don't over think it.",
"Make a photograph conveying the feeling or thought of being hot.",
"Illustrate the word equality today with a photograph that shows your favorite interpretation.",
"Rotate your camera today a bit and make a slightly off-angle photograph. Use the angle to emphasize your subject.",
"Go meta and make a photo of a photo today. Don't just be a copy machine, however. Get creative with composition.",
"We all have some sort of hobby or favorite activity. Make a photo that shows something you enjoy doing.",
"Make a photograph featuring the color yellow today.",
"Make a photograph of the front of a building today. Could be your house, the bank, or city hall.",
"Make a photograph with a low horizon line today.",
"Yellow is an attention-getting color. Make a photograph that is dominated by yellow today.",
"The horizon can be a strong composition element. Make a photograph that emphasizes the horizon today.",
"Make a photograph that emphasizes the dark tones.",
"Create a photograph that illustrations connection.",
"Make a photograph from an unusual point of view.",
"Make a photograph that illustrates a memory from your childhood.",
"Make a photograph dominated by the color orange today.",
"Make a composition today with four elements in it.",
"Make a photograph featuring a metal or metallic object or surface.",
"Frame a view using a door or a window today.",
"Refresh from the summer heat today. Make a photo of water in motion. Freeze it or let it blur!",
"We're all collectors of something. Find an interesting way to display and make a photo of a collection today.",
"Make a photograph of something smooth.",
"Make a photo that has your first letter of your name in it.",
"What has been your favorite Daily Shoot assignment? Give it another go today.",
"Make a photograph today featuring a hand.",
"Make a photograph that is obviously composed using the rule of thirds.",
"Make a photograph that emphasizes the horizon today and post it.",
"Play with reflections in a photograph today.",
"Make a photo of something that reminds you of that sense of childhood wonder.",
"Make a photograph that features the color green today.",
"Make a photograph featuring a circle of some sort today.",
"Make a photograph featuring parallel lines today.",
"Make a photograph with a different point of view than you normally would consider.",
"What's a photograph you've wanted to make for a while but haven't for some reason? Make it today.",
"Make a photograph composed of earth tones today. Use contrast and composition to provide visual excitement.",
"Create a photo with a single element, no distractions, &amp; lots of contrast.",
"Make a photograph with an emphasis on the sky today.",
"It's all about the color red today. Make a photograph that is full of a red subject.",
"Make a photograph of a plastic object that you’ve used today.",
"Make a low contrast photograph today dominated by light tones.",
"Exercise your photographic green thumb and make a photograph of a plant today.",
"Illustrate attraction in a photograph today.",
"Illustrate your idea of a relaxing Sunday today in a photograph.",
"What's it like outside where you are today? Make a photograph that shows the world.",
"Make a photograph featuring a natural material.",
"Make a photograph dominated by dark tones today.",
"Make a photograph of a beautiful simple shape, such as an egg, today. Utilize lighting and focus to make it sing.",
"Make a photograph of a path, road, or trail that leads the viewer's eye through the frame.",
"Make a photograph today of an interesting subject with as vertical or high a point of view as you can manage.",
"Make a photograph that conveys a somber or respectful mood today.",
"Illustrate the word equality today with a photograph that shows your favorite interpretation.",
"Make a photograph with a photograph. Find a cherished print and compose it in a larger scene.",
"Make a photograph that features the color yellow in some way or another.",
"Go old-school today and make a photograph that either features an old subject or simply looks old.",
"Make a photograph that conveys or illustrates a sense of music.",
"Make a photograph through or of a door or window today.",
"Make a sharp photo today any way you interpret it, either tack-sharp focus or a subject that is sharp itself.",
"Make a photograph today with a central point of interest in it.",
"Make a photograph that illustrates the idea of connection.",
"Bright, vivid colors can draw attention and add pop to a photo. Make a photo that has vivid colors today.",
"Construction seems to be perpetual: streets, sidewalks, buildings. Make a photo of something under construction today.",
"Lose the rectangle today. Make a photograph with a square (1:1) aspect ratio and post it. Crop if needed.",
"Make a photograph today with a central point of interest in it.",
"Make an interesting photograph of something mundane and ordinary today.",
"Sunday Challenge (by popular request): Make a self-portrait, with or without the camera in the frame.",
"Make a photo without composing by looking through the viewfinder: over your head, from the hip, on the ground, etc.",
"Breakfast, lunch, or dinner. Make a photograph of a yummy part of one of your meals today.",
"The economy is in the news all the time. Make a photo that illustrates the economy or its impact on you in some way.",
"Rules can be stifling if taken to extremes. Break the rules today with focus, composition, etc, and see what happens.",
"Make a photograph that illustrates an aspect of communication.",
"Make a photo that captures the day for you wherever you are.",
"Make a photograph that expresses humor or laughter today.",
"The horizon can be a strong composition element. Make a photograph that emphasizes the horizon today.",
"Make a photograph that illustrates technology today.",
"For the last Daily Shoot assignment, make a photograph today that is important to you. One that says what you want to say"
];

function setSharing(themeIndex) {
  var twitter = document.getElementById("twitter-button");
  twitter.href = "https://twitter.com/intent/tweet?button_hashtag=ds" + themeIndex + "&text=" + encodeURIComponent(themes[themeIndex]);

  var encodedHash = encodeURIComponent("#ds" + themeIndex);
  document.getElementById("flickr-search").href = "https://www.flickr.com/search/?q=" + encodedHash;
  document.getElementById("twitter-search").href = "https://twitter.com/search?q=" + encodedHash;
}

function setTheme(container, themeIndex) {
  if (container) {
    container.innerHTML = themeIndex + ". " + themes[themeIndex];
    container.className = "";
    setSharing(themeIndex);
  }
}

function getRandomIndex() {
  return Math.floor(Math.random() * themes.length);
}

function getTodayIndex() {
  return Math.floor(new Date().getTime() / (1000 * 60 * 60 * 24)) % themes.length;
}

setTheme(document.getElementById("random-theme"), getRandomIndex());
setTheme(document.getElementById("today-theme"), getTodayIndex());

!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
